version: '3'
services:

  covid19-bot:
    image: covid19-bot
    container_name: covid19-bot
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - './data:/srv/covid19-bot/data'
    links:
      - covid19-bot-tor

  covid19-bot-tor:
    image: dperson/torproxy
    container_name: covid19-bot-tor
    ports:
      - 8118:8118
      - 9050:9050